/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface DFArenaInitializeInterface extends ethers.utils.Interface {
  functions: {
    "init(tuple,tuple)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "init",
    values: [
      {
        START_PAUSED: boolean;
        ADMIN_CAN_ADD_PLANETS: boolean;
        LOCATION_REVEAL_COOLDOWN: BigNumberish;
        TOKEN_MINT_END_TIMESTAMP: BigNumberish;
        WORLD_RADIUS_LOCKED: boolean;
        WORLD_RADIUS_MIN: BigNumberish;
        DISABLE_ZK_CHECKS: boolean;
        PLANETHASH_KEY: BigNumberish;
        SPACETYPE_KEY: BigNumberish;
        BIOMEBASE_KEY: BigNumberish;
        PERLIN_MIRROR_X: boolean;
        PERLIN_MIRROR_Y: boolean;
        PERLIN_LENGTH_SCALE: BigNumberish;
        MAX_NATURAL_PLANET_LEVEL: BigNumberish;
        TIME_FACTOR_HUNDREDTHS: BigNumberish;
        PERLIN_THRESHOLD_1: BigNumberish;
        PERLIN_THRESHOLD_2: BigNumberish;
        PERLIN_THRESHOLD_3: BigNumberish;
        INIT_PERLIN_MIN: BigNumberish;
        INIT_PERLIN_MAX: BigNumberish;
        SPAWN_RIM_AREA: BigNumberish;
        BIOME_THRESHOLD_1: BigNumberish;
        BIOME_THRESHOLD_2: BigNumberish;
        PLANET_LEVEL_THRESHOLDS: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
        PLANET_RARITY: BigNumberish;
        PLANET_TRANSFER_ENABLED: boolean;
        PLANET_TYPE_WEIGHTS: [
          [
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ]
          ],
          [
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ]
          ],
          [
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ]
          ],
          [
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ]
          ]
        ];
        SILVER_SCORE_VALUE: BigNumberish;
        ARTIFACT_POINT_VALUES: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
        PHOTOID_ACTIVATION_DELAY: BigNumberish;
        SPACE_JUNK_ENABLED: boolean;
        SPACE_JUNK_LIMIT: BigNumberish;
        PLANET_LEVEL_JUNK: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
        ABANDON_SPEED_CHANGE_PERCENT: BigNumberish;
        ABANDON_RANGE_CHANGE_PERCENT: BigNumberish;
        CAPTURE_ZONES_ENABLED: boolean;
        CAPTURE_ZONE_COUNT: BigNumberish;
        CAPTURE_ZONE_CHANGE_BLOCK_INTERVAL: BigNumberish;
        CAPTURE_ZONE_RADIUS: BigNumberish;
        CAPTURE_ZONE_PLANET_LEVEL_SCORE: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
        CAPTURE_ZONE_HOLD_BLOCKS_REQUIRED: BigNumberish;
        CAPTURE_ZONES_PER_5000_WORLD_RADIUS: BigNumberish;
        TARGET_PLANETS: boolean;
        CLAIM_VICTORY_ENERGY_PERCENT: BigNumberish;
        MANUAL_SPAWN: boolean;
        MODIFIERS: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
        SPACESHIPS: [boolean, boolean, boolean, boolean, boolean];
        RANDOM_ARTIFACTS: boolean;
        NO_ADMIN: boolean;
        INIT_PLANETS: {
          location: BigNumberish;
          x: BigNumberish;
          y: BigNumberish;
          perlin: BigNumberish;
          level: BigNumberish;
          planetType: BigNumberish;
          requireValidLocationId: boolean;
          isTargetPlanet: boolean;
          isSpawnPlanet: boolean;
          blockedPlanetIds: BigNumberish[];
        }[];
        CONFIRM_START: boolean;
        TARGETS_REQUIRED_FOR_VICTORY: BigNumberish;
        BLOCK_MOVES: boolean;
        BLOCK_CAPTURE: boolean;
        TEAMS_ENABLED: boolean;
        NUM_TEAMS: BigNumberish;
        RANKED: boolean;
      },
      {
        allowListEnabled: boolean;
        artifactBaseURI: string;
        allowedAddresses: string[];
      }
    ]
  ): string;

  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;

  events: {};
}

export class DFArenaInitialize extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: DFArenaInitializeInterface;

  functions: {
    init(
      initArgs: {
        START_PAUSED: boolean;
        ADMIN_CAN_ADD_PLANETS: boolean;
        LOCATION_REVEAL_COOLDOWN: BigNumberish;
        TOKEN_MINT_END_TIMESTAMP: BigNumberish;
        WORLD_RADIUS_LOCKED: boolean;
        WORLD_RADIUS_MIN: BigNumberish;
        DISABLE_ZK_CHECKS: boolean;
        PLANETHASH_KEY: BigNumberish;
        SPACETYPE_KEY: BigNumberish;
        BIOMEBASE_KEY: BigNumberish;
        PERLIN_MIRROR_X: boolean;
        PERLIN_MIRROR_Y: boolean;
        PERLIN_LENGTH_SCALE: BigNumberish;
        MAX_NATURAL_PLANET_LEVEL: BigNumberish;
        TIME_FACTOR_HUNDREDTHS: BigNumberish;
        PERLIN_THRESHOLD_1: BigNumberish;
        PERLIN_THRESHOLD_2: BigNumberish;
        PERLIN_THRESHOLD_3: BigNumberish;
        INIT_PERLIN_MIN: BigNumberish;
        INIT_PERLIN_MAX: BigNumberish;
        SPAWN_RIM_AREA: BigNumberish;
        BIOME_THRESHOLD_1: BigNumberish;
        BIOME_THRESHOLD_2: BigNumberish;
        PLANET_LEVEL_THRESHOLDS: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
        PLANET_RARITY: BigNumberish;
        PLANET_TRANSFER_ENABLED: boolean;
        PLANET_TYPE_WEIGHTS: [
          [
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ]
          ],
          [
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ]
          ],
          [
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ]
          ],
          [
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ]
          ]
        ];
        SILVER_SCORE_VALUE: BigNumberish;
        ARTIFACT_POINT_VALUES: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
        PHOTOID_ACTIVATION_DELAY: BigNumberish;
        SPACE_JUNK_ENABLED: boolean;
        SPACE_JUNK_LIMIT: BigNumberish;
        PLANET_LEVEL_JUNK: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
        ABANDON_SPEED_CHANGE_PERCENT: BigNumberish;
        ABANDON_RANGE_CHANGE_PERCENT: BigNumberish;
        CAPTURE_ZONES_ENABLED: boolean;
        CAPTURE_ZONE_COUNT: BigNumberish;
        CAPTURE_ZONE_CHANGE_BLOCK_INTERVAL: BigNumberish;
        CAPTURE_ZONE_RADIUS: BigNumberish;
        CAPTURE_ZONE_PLANET_LEVEL_SCORE: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
        CAPTURE_ZONE_HOLD_BLOCKS_REQUIRED: BigNumberish;
        CAPTURE_ZONES_PER_5000_WORLD_RADIUS: BigNumberish;
        TARGET_PLANETS: boolean;
        CLAIM_VICTORY_ENERGY_PERCENT: BigNumberish;
        MANUAL_SPAWN: boolean;
        MODIFIERS: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
        SPACESHIPS: [boolean, boolean, boolean, boolean, boolean];
        RANDOM_ARTIFACTS: boolean;
        NO_ADMIN: boolean;
        INIT_PLANETS: {
          location: BigNumberish;
          x: BigNumberish;
          y: BigNumberish;
          perlin: BigNumberish;
          level: BigNumberish;
          planetType: BigNumberish;
          requireValidLocationId: boolean;
          isTargetPlanet: boolean;
          isSpawnPlanet: boolean;
          blockedPlanetIds: BigNumberish[];
        }[];
        CONFIRM_START: boolean;
        TARGETS_REQUIRED_FOR_VICTORY: BigNumberish;
        BLOCK_MOVES: boolean;
        BLOCK_CAPTURE: boolean;
        TEAMS_ENABLED: boolean;
        NUM_TEAMS: BigNumberish;
        RANKED: boolean;
      },
      auxArgs: {
        allowListEnabled: boolean;
        artifactBaseURI: string;
        allowedAddresses: string[];
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  init(
    initArgs: {
      START_PAUSED: boolean;
      ADMIN_CAN_ADD_PLANETS: boolean;
      LOCATION_REVEAL_COOLDOWN: BigNumberish;
      TOKEN_MINT_END_TIMESTAMP: BigNumberish;
      WORLD_RADIUS_LOCKED: boolean;
      WORLD_RADIUS_MIN: BigNumberish;
      DISABLE_ZK_CHECKS: boolean;
      PLANETHASH_KEY: BigNumberish;
      SPACETYPE_KEY: BigNumberish;
      BIOMEBASE_KEY: BigNumberish;
      PERLIN_MIRROR_X: boolean;
      PERLIN_MIRROR_Y: boolean;
      PERLIN_LENGTH_SCALE: BigNumberish;
      MAX_NATURAL_PLANET_LEVEL: BigNumberish;
      TIME_FACTOR_HUNDREDTHS: BigNumberish;
      PERLIN_THRESHOLD_1: BigNumberish;
      PERLIN_THRESHOLD_2: BigNumberish;
      PERLIN_THRESHOLD_3: BigNumberish;
      INIT_PERLIN_MIN: BigNumberish;
      INIT_PERLIN_MAX: BigNumberish;
      SPAWN_RIM_AREA: BigNumberish;
      BIOME_THRESHOLD_1: BigNumberish;
      BIOME_THRESHOLD_2: BigNumberish;
      PLANET_LEVEL_THRESHOLDS: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ];
      PLANET_RARITY: BigNumberish;
      PLANET_TRANSFER_ENABLED: boolean;
      PLANET_TYPE_WEIGHTS: [
        [
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]
        ],
        [
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]
        ],
        [
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]
        ],
        [
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish,
            BigNumberish
          ],
          [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]
        ]
      ];
      SILVER_SCORE_VALUE: BigNumberish;
      ARTIFACT_POINT_VALUES: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ];
      PHOTOID_ACTIVATION_DELAY: BigNumberish;
      SPACE_JUNK_ENABLED: boolean;
      SPACE_JUNK_LIMIT: BigNumberish;
      PLANET_LEVEL_JUNK: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ];
      ABANDON_SPEED_CHANGE_PERCENT: BigNumberish;
      ABANDON_RANGE_CHANGE_PERCENT: BigNumberish;
      CAPTURE_ZONES_ENABLED: boolean;
      CAPTURE_ZONE_COUNT: BigNumberish;
      CAPTURE_ZONE_CHANGE_BLOCK_INTERVAL: BigNumberish;
      CAPTURE_ZONE_RADIUS: BigNumberish;
      CAPTURE_ZONE_PLANET_LEVEL_SCORE: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ];
      CAPTURE_ZONE_HOLD_BLOCKS_REQUIRED: BigNumberish;
      CAPTURE_ZONES_PER_5000_WORLD_RADIUS: BigNumberish;
      TARGET_PLANETS: boolean;
      CLAIM_VICTORY_ENERGY_PERCENT: BigNumberish;
      MANUAL_SPAWN: boolean;
      MODIFIERS: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ];
      SPACESHIPS: [boolean, boolean, boolean, boolean, boolean];
      RANDOM_ARTIFACTS: boolean;
      NO_ADMIN: boolean;
      INIT_PLANETS: {
        location: BigNumberish;
        x: BigNumberish;
        y: BigNumberish;
        perlin: BigNumberish;
        level: BigNumberish;
        planetType: BigNumberish;
        requireValidLocationId: boolean;
        isTargetPlanet: boolean;
        isSpawnPlanet: boolean;
        blockedPlanetIds: BigNumberish[];
      }[];
      CONFIRM_START: boolean;
      TARGETS_REQUIRED_FOR_VICTORY: BigNumberish;
      BLOCK_MOVES: boolean;
      BLOCK_CAPTURE: boolean;
      TEAMS_ENABLED: boolean;
      NUM_TEAMS: BigNumberish;
      RANKED: boolean;
    },
    auxArgs: {
      allowListEnabled: boolean;
      artifactBaseURI: string;
      allowedAddresses: string[];
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    init(
      initArgs: {
        START_PAUSED: boolean;
        ADMIN_CAN_ADD_PLANETS: boolean;
        LOCATION_REVEAL_COOLDOWN: BigNumberish;
        TOKEN_MINT_END_TIMESTAMP: BigNumberish;
        WORLD_RADIUS_LOCKED: boolean;
        WORLD_RADIUS_MIN: BigNumberish;
        DISABLE_ZK_CHECKS: boolean;
        PLANETHASH_KEY: BigNumberish;
        SPACETYPE_KEY: BigNumberish;
        BIOMEBASE_KEY: BigNumberish;
        PERLIN_MIRROR_X: boolean;
        PERLIN_MIRROR_Y: boolean;
        PERLIN_LENGTH_SCALE: BigNumberish;
        MAX_NATURAL_PLANET_LEVEL: BigNumberish;
        TIME_FACTOR_HUNDREDTHS: BigNumberish;
        PERLIN_THRESHOLD_1: BigNumberish;
        PERLIN_THRESHOLD_2: BigNumberish;
        PERLIN_THRESHOLD_3: BigNumberish;
        INIT_PERLIN_MIN: BigNumberish;
        INIT_PERLIN_MAX: BigNumberish;
        SPAWN_RIM_AREA: BigNumberish;
        BIOME_THRESHOLD_1: BigNumberish;
        BIOME_THRESHOLD_2: BigNumberish;
        PLANET_LEVEL_THRESHOLDS: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
        PLANET_RARITY: BigNumberish;
        PLANET_TRANSFER_ENABLED: boolean;
        PLANET_TYPE_WEIGHTS: [
          [
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ]
          ],
          [
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ]
          ],
          [
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ]
          ],
          [
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ]
          ]
        ];
        SILVER_SCORE_VALUE: BigNumberish;
        ARTIFACT_POINT_VALUES: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
        PHOTOID_ACTIVATION_DELAY: BigNumberish;
        SPACE_JUNK_ENABLED: boolean;
        SPACE_JUNK_LIMIT: BigNumberish;
        PLANET_LEVEL_JUNK: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
        ABANDON_SPEED_CHANGE_PERCENT: BigNumberish;
        ABANDON_RANGE_CHANGE_PERCENT: BigNumberish;
        CAPTURE_ZONES_ENABLED: boolean;
        CAPTURE_ZONE_COUNT: BigNumberish;
        CAPTURE_ZONE_CHANGE_BLOCK_INTERVAL: BigNumberish;
        CAPTURE_ZONE_RADIUS: BigNumberish;
        CAPTURE_ZONE_PLANET_LEVEL_SCORE: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
        CAPTURE_ZONE_HOLD_BLOCKS_REQUIRED: BigNumberish;
        CAPTURE_ZONES_PER_5000_WORLD_RADIUS: BigNumberish;
        TARGET_PLANETS: boolean;
        CLAIM_VICTORY_ENERGY_PERCENT: BigNumberish;
        MANUAL_SPAWN: boolean;
        MODIFIERS: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
        SPACESHIPS: [boolean, boolean, boolean, boolean, boolean];
        RANDOM_ARTIFACTS: boolean;
        NO_ADMIN: boolean;
        INIT_PLANETS: {
          location: BigNumberish;
          x: BigNumberish;
          y: BigNumberish;
          perlin: BigNumberish;
          level: BigNumberish;
          planetType: BigNumberish;
          requireValidLocationId: boolean;
          isTargetPlanet: boolean;
          isSpawnPlanet: boolean;
          blockedPlanetIds: BigNumberish[];
        }[];
        CONFIRM_START: boolean;
        TARGETS_REQUIRED_FOR_VICTORY: BigNumberish;
        BLOCK_MOVES: boolean;
        BLOCK_CAPTURE: boolean;
        TEAMS_ENABLED: boolean;
        NUM_TEAMS: BigNumberish;
        RANKED: boolean;
      },
      auxArgs: {
        allowListEnabled: boolean;
        artifactBaseURI: string;
        allowedAddresses: string[];
      },
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    init(
      initArgs: {
        START_PAUSED: boolean;
        ADMIN_CAN_ADD_PLANETS: boolean;
        LOCATION_REVEAL_COOLDOWN: BigNumberish;
        TOKEN_MINT_END_TIMESTAMP: BigNumberish;
        WORLD_RADIUS_LOCKED: boolean;
        WORLD_RADIUS_MIN: BigNumberish;
        DISABLE_ZK_CHECKS: boolean;
        PLANETHASH_KEY: BigNumberish;
        SPACETYPE_KEY: BigNumberish;
        BIOMEBASE_KEY: BigNumberish;
        PERLIN_MIRROR_X: boolean;
        PERLIN_MIRROR_Y: boolean;
        PERLIN_LENGTH_SCALE: BigNumberish;
        MAX_NATURAL_PLANET_LEVEL: BigNumberish;
        TIME_FACTOR_HUNDREDTHS: BigNumberish;
        PERLIN_THRESHOLD_1: BigNumberish;
        PERLIN_THRESHOLD_2: BigNumberish;
        PERLIN_THRESHOLD_3: BigNumberish;
        INIT_PERLIN_MIN: BigNumberish;
        INIT_PERLIN_MAX: BigNumberish;
        SPAWN_RIM_AREA: BigNumberish;
        BIOME_THRESHOLD_1: BigNumberish;
        BIOME_THRESHOLD_2: BigNumberish;
        PLANET_LEVEL_THRESHOLDS: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
        PLANET_RARITY: BigNumberish;
        PLANET_TRANSFER_ENABLED: boolean;
        PLANET_TYPE_WEIGHTS: [
          [
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ]
          ],
          [
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ]
          ],
          [
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ]
          ],
          [
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ]
          ]
        ];
        SILVER_SCORE_VALUE: BigNumberish;
        ARTIFACT_POINT_VALUES: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
        PHOTOID_ACTIVATION_DELAY: BigNumberish;
        SPACE_JUNK_ENABLED: boolean;
        SPACE_JUNK_LIMIT: BigNumberish;
        PLANET_LEVEL_JUNK: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
        ABANDON_SPEED_CHANGE_PERCENT: BigNumberish;
        ABANDON_RANGE_CHANGE_PERCENT: BigNumberish;
        CAPTURE_ZONES_ENABLED: boolean;
        CAPTURE_ZONE_COUNT: BigNumberish;
        CAPTURE_ZONE_CHANGE_BLOCK_INTERVAL: BigNumberish;
        CAPTURE_ZONE_RADIUS: BigNumberish;
        CAPTURE_ZONE_PLANET_LEVEL_SCORE: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
        CAPTURE_ZONE_HOLD_BLOCKS_REQUIRED: BigNumberish;
        CAPTURE_ZONES_PER_5000_WORLD_RADIUS: BigNumberish;
        TARGET_PLANETS: boolean;
        CLAIM_VICTORY_ENERGY_PERCENT: BigNumberish;
        MANUAL_SPAWN: boolean;
        MODIFIERS: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
        SPACESHIPS: [boolean, boolean, boolean, boolean, boolean];
        RANDOM_ARTIFACTS: boolean;
        NO_ADMIN: boolean;
        INIT_PLANETS: {
          location: BigNumberish;
          x: BigNumberish;
          y: BigNumberish;
          perlin: BigNumberish;
          level: BigNumberish;
          planetType: BigNumberish;
          requireValidLocationId: boolean;
          isTargetPlanet: boolean;
          isSpawnPlanet: boolean;
          blockedPlanetIds: BigNumberish[];
        }[];
        CONFIRM_START: boolean;
        TARGETS_REQUIRED_FOR_VICTORY: BigNumberish;
        BLOCK_MOVES: boolean;
        BLOCK_CAPTURE: boolean;
        TEAMS_ENABLED: boolean;
        NUM_TEAMS: BigNumberish;
        RANKED: boolean;
      },
      auxArgs: {
        allowListEnabled: boolean;
        artifactBaseURI: string;
        allowedAddresses: string[];
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    init(
      initArgs: {
        START_PAUSED: boolean;
        ADMIN_CAN_ADD_PLANETS: boolean;
        LOCATION_REVEAL_COOLDOWN: BigNumberish;
        TOKEN_MINT_END_TIMESTAMP: BigNumberish;
        WORLD_RADIUS_LOCKED: boolean;
        WORLD_RADIUS_MIN: BigNumberish;
        DISABLE_ZK_CHECKS: boolean;
        PLANETHASH_KEY: BigNumberish;
        SPACETYPE_KEY: BigNumberish;
        BIOMEBASE_KEY: BigNumberish;
        PERLIN_MIRROR_X: boolean;
        PERLIN_MIRROR_Y: boolean;
        PERLIN_LENGTH_SCALE: BigNumberish;
        MAX_NATURAL_PLANET_LEVEL: BigNumberish;
        TIME_FACTOR_HUNDREDTHS: BigNumberish;
        PERLIN_THRESHOLD_1: BigNumberish;
        PERLIN_THRESHOLD_2: BigNumberish;
        PERLIN_THRESHOLD_3: BigNumberish;
        INIT_PERLIN_MIN: BigNumberish;
        INIT_PERLIN_MAX: BigNumberish;
        SPAWN_RIM_AREA: BigNumberish;
        BIOME_THRESHOLD_1: BigNumberish;
        BIOME_THRESHOLD_2: BigNumberish;
        PLANET_LEVEL_THRESHOLDS: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
        PLANET_RARITY: BigNumberish;
        PLANET_TRANSFER_ENABLED: boolean;
        PLANET_TYPE_WEIGHTS: [
          [
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ]
          ],
          [
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ]
          ],
          [
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ]
          ],
          [
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ],
            [
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish,
              BigNumberish
            ]
          ]
        ];
        SILVER_SCORE_VALUE: BigNumberish;
        ARTIFACT_POINT_VALUES: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
        PHOTOID_ACTIVATION_DELAY: BigNumberish;
        SPACE_JUNK_ENABLED: boolean;
        SPACE_JUNK_LIMIT: BigNumberish;
        PLANET_LEVEL_JUNK: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
        ABANDON_SPEED_CHANGE_PERCENT: BigNumberish;
        ABANDON_RANGE_CHANGE_PERCENT: BigNumberish;
        CAPTURE_ZONES_ENABLED: boolean;
        CAPTURE_ZONE_COUNT: BigNumberish;
        CAPTURE_ZONE_CHANGE_BLOCK_INTERVAL: BigNumberish;
        CAPTURE_ZONE_RADIUS: BigNumberish;
        CAPTURE_ZONE_PLANET_LEVEL_SCORE: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
        CAPTURE_ZONE_HOLD_BLOCKS_REQUIRED: BigNumberish;
        CAPTURE_ZONES_PER_5000_WORLD_RADIUS: BigNumberish;
        TARGET_PLANETS: boolean;
        CLAIM_VICTORY_ENERGY_PERCENT: BigNumberish;
        MANUAL_SPAWN: boolean;
        MODIFIERS: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
        SPACESHIPS: [boolean, boolean, boolean, boolean, boolean];
        RANDOM_ARTIFACTS: boolean;
        NO_ADMIN: boolean;
        INIT_PLANETS: {
          location: BigNumberish;
          x: BigNumberish;
          y: BigNumberish;
          perlin: BigNumberish;
          level: BigNumberish;
          planetType: BigNumberish;
          requireValidLocationId: boolean;
          isTargetPlanet: boolean;
          isSpawnPlanet: boolean;
          blockedPlanetIds: BigNumberish[];
        }[];
        CONFIRM_START: boolean;
        TARGETS_REQUIRED_FOR_VICTORY: BigNumberish;
        BLOCK_MOVES: boolean;
        BLOCK_CAPTURE: boolean;
        TEAMS_ENABLED: boolean;
        NUM_TEAMS: BigNumberish;
        RANKED: boolean;
      },
      auxArgs: {
        allowListEnabled: boolean;
        artifactBaseURI: string;
        allowedAddresses: string[];
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
