/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface DFCaptureFacetInterface extends ethers.utils.Interface {
  functions: {
    "capturePlanet(uint256)": FunctionFragment;
    "getIntFromUInt(uint256)": FunctionFragment;
    "invadePlanet(uint256[2],uint256[2][2],uint256[2],uint256[9])": FunctionFragment;
    "planetInCaptureZone(uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "capturePlanet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getIntFromUInt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "invadePlanet",
    values: [
      [BigNumberish, BigNumberish],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      [BigNumberish, BigNumberish],
      [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "planetInCaptureZone",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "capturePlanet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIntFromUInt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "invadePlanet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "planetInCaptureZone",
    data: BytesLike
  ): Result;

  events: {
    "PlanetCaptured(address,uint256)": EventFragment;
    "PlanetInvaded(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "PlanetCaptured"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PlanetInvaded"): EventFragment;
}

export type PlanetCapturedEvent = TypedEvent<
  [string, BigNumber] & { player: string; loc: BigNumber }
>;

export type PlanetInvadedEvent = TypedEvent<
  [string, BigNumber] & { player: string; loc: BigNumber }
>;

export class DFCaptureFacet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: DFCaptureFacetInterface;

  functions: {
    capturePlanet(
      locationId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getIntFromUInt(
      n: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    invadePlanet(
      _a: [BigNumberish, BigNumberish],
      _b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      _c: [BigNumberish, BigNumberish],
      _input: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    planetInCaptureZone(
      x: BigNumberish,
      y: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  capturePlanet(
    locationId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getIntFromUInt(
    n: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  invadePlanet(
    _a: [BigNumberish, BigNumberish],
    _b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
    _c: [BigNumberish, BigNumberish],
    _input: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  planetInCaptureZone(
    x: BigNumberish,
    y: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    capturePlanet(
      locationId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getIntFromUInt(
      n: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    invadePlanet(
      _a: [BigNumberish, BigNumberish],
      _b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      _c: [BigNumberish, BigNumberish],
      _input: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      overrides?: CallOverrides
    ): Promise<void>;

    planetInCaptureZone(
      x: BigNumberish,
      y: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "PlanetCaptured(address,uint256)"(
      player?: null,
      loc?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { player: string; loc: BigNumber }
    >;

    PlanetCaptured(
      player?: null,
      loc?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { player: string; loc: BigNumber }
    >;

    "PlanetInvaded(address,uint256)"(
      player?: null,
      loc?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { player: string; loc: BigNumber }
    >;

    PlanetInvaded(
      player?: null,
      loc?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { player: string; loc: BigNumber }
    >;
  };

  estimateGas: {
    capturePlanet(
      locationId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getIntFromUInt(
      n: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    invadePlanet(
      _a: [BigNumberish, BigNumberish],
      _b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      _c: [BigNumberish, BigNumberish],
      _input: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    planetInCaptureZone(
      x: BigNumberish,
      y: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    capturePlanet(
      locationId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getIntFromUInt(
      n: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    invadePlanet(
      _a: [BigNumberish, BigNumberish],
      _b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      _c: [BigNumberish, BigNumberish],
      _input: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    planetInCaptureZone(
      x: BigNumberish,
      y: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
